### ISSUE TITLE
Trying on a ASUS p8p67 LE edition

### ISSUE THREAD

**Issue by vbraque** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#10]
Hi from Spain.
I'm trying my first hackingtosh on my old Asus p8p67 LE edition. That's important, not PRO or EVO editions.

https://www.asus.com/Motherboards/P8P67_LE/specifications/

I've just installed with unibeast/multibest but no ethernet card is detected. I know one of the main differences between PRO and LE editions is the lan driver. The mine one is a Realtek 8111e.
I've tried some versions of multibeast kext driver, but it's not detected.
Do you think if I copy all your EFI folder and change the lan driver would be detected?

I've also another problem with graphics card. Detects my ATI Radeon HD 5770, but resolution shown is 1280x1024.. my actual monitor supports 1650x1050. I've just update this value in one section via Clover configurator, but nothing happens.
Any help would be appreciated.
I read everything I can.
Tks.

**Comment by vbraque** [comment]
Of course I'll delete kexts and actions relative to Nvidia drivers. No problem about ATI Radeon 5770 HD detection, just native resolution of my monitor ( Acer AL2216W, natively 1650x1050)

**Comment by vbraque** [comment]
And of course my bios settings are just like yours. In fact, my bios version is newer (3801 instead of 3602).

**Comment by rafaelmaeuer** [comment]
Hey, 

regarding the gpu: have you tried using [WEG](https://github.com/acidanthera/WhateverGreen/) and [Lilu](https://github.com/acidanthera/Lilu) kexts? Nevertheless the card might be unsupported, I would stick to one of those: [gpu-buyers-guide](https://khronokernel-3.gitbook.io/gpu-buyers-guide/modern-gpus/amd-gpu)

For ethernet I would give [OS-X-Realtek-Network](https://github.com/RehabMan/OS-X-Realtek-Network) kext a try...
Just copying my EFI folder might not work, as I am using IntelMausiEthernet kext.

**Comment by vbraque** [comment]
Thanks for you quick response.
I'm afraid ATI Radeon 5770 HD is not supported in Mojava and Catalina...
see this thread...https://www.tonymacx86.com/threads/hd-5770-on-10-14-mojave-is-not-working-fine.260847/

So perhaps I'll try with High Sierra, last supported version.
In fact, there no exists AMD5000Controller.kext in /Library/Extensions.

Opps! My Realtek ethernet card works okay.

Thanks again

**Comment by vbraque** [comment]
Hi again.
I know your github project is about Catalina version, anyway I ask you about High Sierra edition.
I've been trying Unibeast/Multibeast method. Everything was okay: creating bootable usb, booting from clover, installation (including high ressolution detection!!), but... an error at the end. No mor info about it. Perhaps I must try a second time with -v (verbose). 
But I've tried a second method: create bootable usb by "createmedia" instruction, clover boot + clover configuration, and the boot from usb. I've included the High Sierra kexts similar to Catalina: Lilu, Whatevergreen, FakeSMC, Reatltek8111 ....
I've paste a sample config.plist from an Ivy Bridge... Note my mobo is a Sandy Bridge, just  the preceeding generation, so it's not the exact one. And the result: clover boots from usb but crash where installation starts. A disaster!
¿Do you think your config.plist could be better or it's ready-made for Catalina?
I can't find Sandy bridge sample config.plist anywhere.
¿Must I try a second time with Unibesat/Multibeat verbose? ¿Must I try to run Multibeast becase it has a Sandy bridge injection to EFI folder?
tks

**Comment by rafaelmaeuer** [comment]
Hey have a look at [this](https://www.hackintosh-forum.de/forum/thread/35707-high-sierra-auf-p8p67-pro/?pageNo=1) post. Alternatively you can go back through my git and check the first version of config.plist, I startet this hack with High Sierra...

**Comment by vbraque** [comment]
Hi Rafael, thanks again.
Installation of High Sierra okay... graphics card detected in hi res with no aditional kexts (apple is ati native) and also ethernet card detected with the corresponding kext for realtek 8111.
But.... doesn't detects audio, je, je... It's was working fine with the first attempt with Catalina.
I'll try this video... https://youtu.be/AVkX4NrdspY. I suppose I'll fix it.

Any suggestions to activate usb 3.0?
Actually, I've disabled usb 3.0 support on bios.
Must I try to enable it and then try with a specific kext to become ready?

**Comment by rafaelmaeuer** [comment]
Hey congrats. 
I also have my built-in USB3 disabled, but you can give it a try with [GenericUSBXHCI.kext](https://github.com/rafaelmaeuer/Asus-P8P67Pro-Hackintosh#internal-usb3-with-shutdown-issue-rehabmanos-x-generic-usb3). I use an Inateck KT4006 PCI-E card as you can see in the [readme](https://github.com/rafaelmaeuer/Asus-P8P67Pro-Hackintosh#usb3).

**Comment by vbraque** [comment]
Sound working okay!!!. I was easy..Just inject the correct layout code for sound card in the Device section in config.plist.
Next challenge: usb 3.0.

And one important doubt: Although I have copied /EFI folder from bootable usb to muy SSD device, I cant boot directly from my SSD disk. Unfortunately I only can boot from usb (UEFI mode). My bios shows 3 "mac osx" disks, but none of them boots. I have read tutorial about that but no succeed.

**Comment by vbraque** [comment]
Well, I think I can live without usb 3.0... it will be disabled on bios forever ;)
I prefer not "ghost" shutdowns for this reason.
usb 2.0 is enough for me.
