### ISSUE TITLE
Unable to boot from SSD

### ISSUE THREAD

**Issue by Gorbataras** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#11]
I was able to install MacOS. Everything is working ok but the only issue is that I am unable to boot from the SSD. I moved my EFI from the USB to the SSD EFI partition but the bios does not find it.

**Comment by rafaelmaeuer** [comment]
Were you able to solve the problem? Would you share the solution for others? When Bios doesn't find Clover on the SSD I usually add clover boot option manually with [EasyUEFI](https://www.easyuefi.com/index-us.html) from my parallel Windows Install as described [here](https://www.insanelymac.com/forum/topic/310038-manually-install-clover-and-configure-boot-priority-with-easyuefi-in-windows/).
