### ISSUE TITLE
RX 480 Black Screen in Installer

### ISSUE THREAD

**Issue by MrPerson156** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#12]
Hi, 
I am trying to install Catalina 10.15.5 on my PC, specs below. I have an RX 480 and when booting into the installer, after the apple logo bar gets to about two thirds, the screen goes black. My TV is still getting a signal. I have also tried with my monitor which works with my Mac mini, to be sure its not the tv. The same happens with verbose mode, and I have tried lots of boot args, patches, eat that I have seen online. The only semi-success I have had is when I left the PC for about an hour whilst I was elsewhere, and when I returned the PC was I sleep mode, when I turned it back on, the installer was displaying on the screen but the keyboard and mouse wouldn't work. Any help would be great.

SPECS:
P8P67 PRo Rev.3
i5 2500K
RX 480
16GB DDR3 1600 RAM

**Comment by MrPerson156** [comment]
UPDATE: Managed to fix this! 
I formatted the EFI Partition of the USB, reinstalled clover according to the guide.

I then copied the kexts from your EFI Folder, aswell as the driver folders I also transferred the api patched folder, but not the origin folder as this caused a kernel panic. 

I also added the GPU compatibility check bootleg which you mentioned.

Now Booted into the installer perfectly, Ill let you know what happens with the OS.

**Comment by MrPerson156** [comment]
The OS installed fine, but when booting Into the OS, I get a kernel panic, then after 10 seconds, windows boots.

**Comment by rafaelmaeuer** [comment]
can you capture the last lines of verbose log before kernel panic?

**Comment by MrPerson156** [comment]
Hi, I managed to fix it temporarily by removing all of the boot args and changing USB ports. No im in the OS just fine, but im struggling to get sound working, is this a normal issue?
Thanks.

**Comment by MrPerson156** [comment]
Just fixed it, I had the wrong device selected.
Thanks for the help.
