### ISSUE TITLE
Installer gets stuck on Apple Logo

### ISSUE THREAD

**Issue by Aidan-Wolf** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#14]
Hi Rafael - first of all I must thank you for generously posting your setup and instructions here. I happen to have a Hackintosh very similar to your setup:  

ASUS P8P67 PRO, 
i7-2700K, 
XFX RX570, 
32gb 1600ghz ram. 

BIOS is P8P67-PRO-ASUS-3602.ROM

It has been working well with Yosemite for years and is mostly used as a DAW (not with the XFX though, which isn't properly recognised by my Yosemite setup).

I believe I have followed your instructions faithfully, and copied your EFI folder to my clover bootloader.

The Catalina installer was made from the latest download at the Apple Store.

Unfortunately the installer blocks on the the Apple logo, without the progress bar. I am attaching a photo of my verbose screen. I'm sure you must be busy, but if the solution is something simple I would greatly appreciate your help and hopefully be able to repay your kindness. Thanks, Aidan

![IMG_1735](https://user-images.githubusercontent.com/74186290/98538112-92e14480-228a-11eb-9121-e5237a1a06cf.JPG)

**Comment by rafaelmaeuer** [comment]
Hello @Aidan-Wolf and sorry for the long waiting.
As you correctly assumed I don't have much time at the moment.
Nevertheless, does it always stops at `FakeSMCKeystore: started`?
Can you try this: https://www.reddit.com/r/hackintosh/comments/bufq2g/restarting_at_fakesmckeystore_started/

**Comment by Aidan-Wolf** [comment]
Thanks for your kind answer - I went through several bios resets. It always seems to stop at FakeSMCKeystore: started .I have also tried other install methods, including OpenCore, with all tests passed, but it was useless. Maybe my mb has some kind of defect. Works great with Yosemite though, booting with multibeast. TIme to build a new DAW, I guess...

**Comment by rafaelmaeuer** [comment]
Did you try to install Big Sur with OpenCore? Please test the most recent update of this repo or close the issue.
