### ISSUE TITLE
MacOS not booting from SSD

### ISSUE THREAD

**Issue by GhencianTimotei** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#15]
I followed every step from your list. I managed to install it and start it just fine, BUT I could not manage to boot it from SSD. After the installation was completed, using the fresh os I followed the steps for creating a bootable UEFI USB, but this time for the SSD. In the and I can see the EFI folder from the SSD, bot in the BIOS I can't find my SSD, only may UEFI USB.
If you need more information let me know.
Thanks!

**Comment by rafaelmaeuer** [comment]
Hey @GhencianTimotei maybe you need to add it manually?
Have a look here: [Restoring UEFI boot entry](https://www.thomas-krenn.com/en/wiki/Restoring_UEFI_boot_entry_via_motherboard_replacement_or_BIOS_update) and here: [UEFI clover boot option](https://www.tonymacx86.com/threads/solved-uefi-clover-boot-option-gone-after-bios-update.211715/#post-1409404)

**Comment by GhencianTimotei** [comment]
The second link did the trick for me :) 
Thanks a lot, man. I was working on this for a week and didn't have any success, but now it's working.
