### ISSUE TITLE
What about Big Sur?

### ISSUE THREAD

**Issue by Qraxin** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#17]
Hello!
Do you try to install Big Sur on P8P67?
My attempts were unsuccessful with Clover and Opencore.

**Comment by rafaelmaeuer** [comment]
Yes it is planned, the update should follow this month...

**Comment by rafaelmaeuer** [comment]
So my first try with Clover r5128 fails with this error:

![IMG_7632](https://user-images.githubusercontent.com/6418459/104856720-a3f6a380-5914-11eb-8f39-c983c1efd4bf.jpg)

It seems that there are major changes on the kernelcache architecture and how the boot process works with big sur ([link](https://github.com/CloverHackyColor/CloverBootloader/issues/190#issuecomment-650844640))

My hope was that the kernel cache problem would become better with the update - it seems not to be the case...
Need to give it another try or one with opencore... how far did you get @Qraxin ?

**Comment by rafaelmaeuer** [comment]
It seems that someone has been [successful](https://www.hackintosh-montreal.com/t10722-big-sur-on-asus-p8p67-rev-3-1) with big sur on a p8p67 rev 3.1.

**Comment by Qraxin** [comment]
Hey @rafaelmaeuer, I have successful Big Sur installation with OpenCore.
I created repo with my EFI folder. You can try with it.
https://github.com/Qraxin/Asus-P8P67-OpenCore-EFI

**Comment by rafaelmaeuer** [comment]
Nice work, I got a working Big Sur installation with it - thanks a lot!
One issue remains: I cannot get a good resolution with OpenCanopy (boot picker).
The resolution fails back to 1024x768 resolution. Is this working for you with a high resolution?
I tried almost every imaginable setting in UEFI->Output (including HiDPI-Scale set to 02)...

**Comment by Qraxin** [comment]
@rafaelmaeuer I have a small resolution in OpenCore picker as well. I decided to leave as is.
If you will a good result with it please let me know.

**Comment by rafaelmaeuer** [comment]
I couldn't solve the problem, some of my investigations can be found here: https://github.com/rafaelmaeuer/Asus-P8P67Pro-Hackintosh#boot-resolution. Thanks @Qraxin for your OpenCore EFI which was a good base for the update of Big Sur.
