### ISSUE TITLE
blackscreen on p8p67lx

### ISSUE THREAD

**Issue by Daohuai0913** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#18]
Hello, thanks for this great EFI. But may I ask a  question, My graphic card is 280x CPU is 2500k when I run all the code, the screen will become a black screen, I have tried open core and clover from 10.13.6 to 11.0 the problem is still with, could you help me, please

**Comment by rafaelmaeuer** [comment]
So regarding the GPU R9 280x/380x cards are a hit or miss on compatibility ([link](https://dortania.github.io/GPU-Buyers-Guide/modern-gpus/amd-gpu.html#r7-r9)). 

For CPU use `1539` in PlatformInfo -> Generic -> ProcessorType (OpenCore Configurator). 

Also remove SSDT-PM.aml from EFI\OC\ACPI and temporarily from config.plist: ACPI -> Add -> SSDT-PM.aml -> disable. Create your own SSDT ([link](https://dortania.github.io/OpenCore-Post-Install/universal/pm.html#sandy-and-ivy-bridge-power-management)) and add it again in EFI\OC\ACPI and re-enable in config.plist.

**Comment by Daohuai0913** [comment]
Thanks a lot, I will try
