### ISSUE TITLE
the copy is damaged and can't be used to install MacOS.

### ISSUE THREAD

**Issue by Myeeoo** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#19]
Hello, thank you very much for the EFI you provided. I downloaded and installed it on my p8h67, e31220, geforce GT 730. The system image is Big Sur 11.2 and the boot is OpenCORE. It has entered the installation interface, but the copy is damaged and cannot be used to install MacOS. What's the problem with me? Can you help me? thank you

**Comment by Myeeoo** [comment]
I've tried to change the time

**Comment by rafaelmaeuer** [comment]
Did you tried this: https://osxdaily.com/2019/10/24/fix-install-macos-application-damaged-cant-be-used-error-mac/

**Comment by Myeeoo** [comment]
> Did you tried this: https://osxdaily.com/2019/10/24/fix-install-macos-application-damaged-cant-be-used-error-mac/

Thank you. I verified the installation image on another Mac. It's really bad. I'm really downloading a new image for installation. I'll try again! thank

**Comment by Myeeoo** [comment]
it work， thanks very very much！！
