### ISSUE TITLE
Bigsur 11.3 Sound not Work

### ISSUE THREAD

**Issue by bluelytihing1** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#20]
Hello rafaelmaeuer Thank you for the EFI files P8P67 DELUXE Working perfectly

When I have updated Bigsur 11.3 , I found that the sound is not working. VoodooHDA did not respond. I have tried to fix it but it doesn't work at all.

**Comment by rafaelmaeuer** [comment]
Sorry I don't have access to the machine at the moment so I can't test macOS update 11.3.
Did you tried the latest version of [VoodooHDA](https://sourceforge.net/projects/voodoohda/) or [AppleALC](https://github.com/acidanthera/AppleALC/releases/latest)?

**Comment by bluelything1** [comment]
![FB_IMG_1620317532467](https://user-images.githubusercontent.com/46630980/117331025-84ce5280-aec0-11eb-8e1d-90c10fdf2f6e.jpg)
I fixed a bug by applying a new VoodooHDA patch on / Library / Extension.  Must disable SLP before installing.

**Comment by bluelything1** [comment]
> Hello rafaelmaeuer Thank you for the EFI files P8P67 DELUXE Working perfectly
> 
> When I have updated Bigsur 11.3 , I found that the sound is not working. VoodooHDA did not respond. I have tried to fix it but it doesn't work at all.

( I Fixed Complete VoodooHDA Working)

**Comment by rafaelmaeuer** [comment]
Nice to hear it's working now, could you share your solution?

**Comment by bluelything1** [comment]
latest Bigsur 11.4 Sound Working. In a few days, I'll be sharing with you how to patch Voodoohda.
![Screen Shot 2564-06-18 at 20 49 21](https://user-images.githubusercontent.com/46630980/122575076-8f146c80-d07a-11eb-9599-33499ba17aad.png)

**Comment by bluelything1** [comment]
How to Patch VoodooHDA On Bigsur 11.4
----------------------------------------------------
First Step
1. Open Config.plist On OpenCore Configurator
2. Go to NVRAM -> csr-active-config 00000000 Set 67000000 for Disabled SIP
3. Save And REBOOT
-------------------------
Second Step
1.Check SIP
     1.1 Open Terminal
     1.2 type a Message "csrutil status"  
     1.3 If Show up "System Integrity Protection status: unknown (Custom Configuration)."  Disabled Complete
2.Download AppleHDADisabled.kext & VoodooHDA2.9.7.kext on insanelymac
     2.1 Website https://www.insanelymac.com/forum/topic/314406-voodoohda-297/
3.when Downloading Complete put file VoodooHDA.kext to Desktop
     3.1 Open Terminal
     3.2 type a Message sudo cp -R /Users/(Name)/Desktop/VoodooHDA.kext /Library/Extensions
     3.3 The system ask you to look into System Preferences -> Security and enable here VoodooHDA
     3.4 Reboot
--------------------------
Final Step
1. Put file AppleHDADisabled.kext to EFI->OC->kext
2. Reboot
--------------------------
END

**Comment by rafaelmaeuer** [comment]
Thanks for sharing your results, I added them to the readme. Nevertheless for installation csr `03000000` and for use `01000000` is sufficient. But as for now there is no option to completely activate SIP again after installation - am I right?
