### ISSUE TITLE
asmedia/Renesas controller kext

### ISSUE THREAD

**Issue by Vorshim92** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#22]
[mXHCD.kext.zip](https://github.com/rafaelmaeuer/Asus-P8P67Pro-Hackintosh/files/7794749/mXHCD.kext.zip)
here you are. Use this for the internal usb 3.0 controller that it works up to catalina. Can't find a way to make it work on big sur unfortunately. I can see it loaded in ioreg but doesn't work

**Comment by rafaelmaeuer** [comment]
Thanks for sharing, but as long its not working on big sur or newer this is not so helpful...
