### ISSUE TITLE
Apple HDA fix

### ISSUE THREAD

**Issue by Krazubu** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#3]
Hey, not an issue but an update so you can get nice AppleHDA support :

https://www.insanelymac.com/forum/topic/276380-the-inevitable-p8p67-pro-install-guide/?do=findComment&comment=2657616

**Comment by rafaelmaeuer** [comment]
Hey thanks for the tip, I didn't saw the necessity to apply this update as I have fully functional sound including optical and coax audio using VoodooHDA. Do you have a Hackintosh based on P8P67-Pro?
![Bildschirmfoto 2019-05-08 um 19 07 00](https://user-images.githubusercontent.com/6418459/57393948-84612b00-71c4-11e9-810e-74bf4c667be3.png)

**Comment by rafaelmaeuer** [comment]
Hey I tested the latest version of [acidanthera/AppleALC](https://github.com/acidanthera/AppleALC/releases/) and it works, but without automatic input switch and less available audio devices. So I added AppleALC to available kexts but I will stay with VoodooHDA for now.
