### ISSUE TITLE
Kernel cache crash

### ISSUE THREAD

**Issue by graysham** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#5]
Have seen this mentioned in the troubleshooting section of the readme but with no further info. I have followed the guide letter for letter, but install crashes on boot with this eroor or occasionally seed related error. Have tried various versions of Aptio fix with no joy, have also tried unibeaat Uefi or legacy boot version as well all have crashed out the same way. Any further info anyone can offer..

**Comment by rafaelmaeuer** [comment]
Hey @graysham, I also face this error from time to time, I lately switched from OsxAptioFixDrv to OsxAptioFix2Drv I had the impression the error occurs less frequently then. To pass this error I need to restart multiple times - so my advice is to keep trying restart until it passes with showing a uuid. Also try restarts with power off. I don't know what causes the kernel cache to crash, I noticed little system changes like hardware or Bios-settings can cause this error, but it also occurs from cold-boot too.

**Comment by graysham** [comment]
Hi thanks for the response, does this continue to be an issue after install or is it just leading up to install?

**Comment by graysham** [comment]
sorry didn’t mean to close the issue!

**Comment by rafaelmaeuer** [comment]
This continue to be an issue after install too, but it doesn't occur often and if it most passes after the first or second restart. But finding a permanent solution would be nice! With OsxAptioFixDrv more restarts were required if I remember correctly. But I guess you tried all OsxAptioFixDrv versions? What is your clover version?

**Comment by graysham** [comment]
Clover I have tried the newest one and whatever version is currently bundled with unibeast. I have tried every version of aptiofix I can find and have either hit kernel
Cache error or seed related error thus far with no successful boots into install. Have removed ram apart from two in slots 1 and 3. Removed all drives except target and made sure it’s only in the gray sata slot.

**Comment by rafaelmaeuer** [comment]
Do you have exactly the same mainboard? Which version is your Bios? I will update working bios settings soon, maybe you can check out yours?

**Comment by graysham** [comment]
I have the normal p8p67 as opposed to the pro, bios version 3602, however have seen people who have successfully set up with this motherboard following your guide. Bios settings I have looked at yours and other guides; disabling Bluetooth, usb 3.0

**Comment by graysham** [comment]
Have just tried 10 reboots in a row, stuck at load prelinked kernel with status 0x800000000009
Error loading kernel cache (0x9)

That’s with Aptiofix2

**Comment by graysham** [comment]
Using aptiofix3 I get past kernelcache 90% of the time and hit randomseed error, any tips on that one? I have tried mapping my ram through smbios, does not seemed to have helped.

**Comment by rafaelmaeuer** [comment]
Do you use the config.plist from the repo? What SMBios do you use? iMac17,1 Intel Core i7 6700K @ 4GHz is working good for me.

**Comment by graysham** [comment]
I have yes used the config.plist, also using 17.1 smbios, May have to look at swapping for another motherboard
