### ISSUE TITLE
P8Z68 10.15 Sidecar support

### ISSUE THREAD

**Issue by stonexing** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#8]
It is said that sidecar need HD Graphics Card.
My Card HD4000 (i7-3770)， Your Card HD2500 (i7-2600k) both been support by Hackintosh
So how to enable both HD Graphics and standlone Graphics Card?

**Comment by rafaelmaeuer** [comment]
I haven't installed Catalina yet. As my mainboard has no video out I guess there is no option to activate it. But you can try this reddit post: [Enabling iGPU + GPU](https://www.reddit.com/r/hackintosh/comments/7m8uah/enabling_igpu_gpu/).

**Comment by stonexing** [comment]
I have already get daul output form my gtx760 and HD4000 under catalina。
But sidecar is still not work，as I know it‘s need new HD Graphics with H.265 decode support！

**Comment by rafaelmaeuer** [comment]
Have you been able to get sidecar to work?

**Comment by stonexing** [comment]
No, I haven't.
Maybe we need buy another Graphics Card such as:VEGA64
But It too expensive.

**Comment by rafaelmaeuer** [comment]
I have no iPad to test, but with Big Sur the Sidecar support is shown in system settings:

<img width="875" alt="Bildschirmfoto 2021-02-03 um 10 57 53" src="https://user-images.githubusercontent.com/6418459/106730479-ba884480-660e-11eb-8dad-f41c48fea4e6.png">

Closing for now.
