### ISSUE TITLE
RX580 shows black screen

### ISSUE THREAD

**Issue by kirankumarsripati** [rafaelmaeuer/Asus-P8P67Pro-Hackintosh#9]
Asus P8P67 Pro, i7 2600k, RX 580 Pulse shows a black screen

**Comment by rafaelmaeuer** [comment]
which connector do you use?

**Comment by kirankumarsripati** [comment]
I have a very old monitor which has only 2 options VGA and DVI, I use convertor for both VGA to HDMI and DVI to HDMI to connect to GPU. I even tried DVI directly, but it didn't work. Windows works find.

**Comment by rafaelmaeuer** [comment]
I had problems using DVI on my RX570, so this might be an issue with RX 580 too... best would be if you could try a direct connection without converter... when is the display getting black? Which connection type is working under windows?

**Comment by kirankumarsripati** [comment]
All options work correctly in Windows
1. DVI to HDMI
2. VGA to HDMI
3. DVI to DVI

Clover screen shows, the screen goes blank after all the verbose text finishes.

My AOC monitor don't have an HDMI option, so I can't test it.

**Comment by kirankumarsripati** [comment]
I have Macbook Pro 2015.
DVI to HDMI connector works fine with Macbook Pro, but VGA to HDMI doesn't work.

**Comment by Gorbataras** [comment]
Was there any solution? I am having the same issue except I am not using any adapters. Tried DVI and HDMI. Sapphire Pulse RX850

**Comment by rafaelmaeuer** [comment]
I guess you mean the Sapphire Pulse RX580? I was only able to use my RX570 via HDMI or DP, DVI had these black screen issues. Going to sleep on first boot seem to be a temporary solution: [link](https://www.insanelymac.com/forum/topic/325987-whatevergreen-support-topic/?do=findComment&comment=2646896). Are you able to try DP?

**Comment by kirankumarsripati** [comment]
@rafaelmaeuer & @Gorbataras, I think RX580 GPU has issues if we don't have internal graphics or using old motherboard like ASUS P8P67 Pro.

I tried to install both Catalina & Mojave, both have the same problem of black screen, no success.

**Comment by Gorbataras** [comment]
Looks like it is just an issue of cable. DP -> HDMI cable works.
